// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreatePaymentRequest mirrors REST's createPaymentRequest body plus the
// Idempotency-Key header — gRPC has no header equivalent a client reliably
// sets, so idempotency_key is a first-class message field instead.
// CreatePaymentRequest has no tenant_id field (reserved, not removed --
// field 2 must never be reused by a future field): tenant identity now
// comes from the AUTHENTICATED caller (the x-api-key metadata resolved by
// grpc.TenantAuthInterceptor, see internal/transport/grpc/interceptor_auth.go),
// never a client-supplied value -- a request could otherwise claim any
// tenant it liked (the CRITICAL finding this change closes).
type CreatePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Livemode       bool                   `protobuf:"varint,3,opt,name=livemode,proto3" json:"livemode,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// amount is minor units (cents) — int64, never a float. Locked money
	// invariant (plan "Invarian Uang — Decide Now" item 1).
	Amount        int64             `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Provider      string            `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	PaymentMethod string            `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// source_app/description are the two caller-supplied Envelope fields —
	// see payment.Envelope's doc. Both optional; an empty string is treated
	// as "not set" (plain string, not proto3 `optional`, since that
	// distinction has no meaning either field needs to make).
	SourceApp   string `protobuf:"bytes,9,opt,name=source_app,json=sourceApp,proto3" json:"source_app,omitempty"`
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// callback_url is optional -- see payment.CreatePaymentInput.CallbackURL's
	// doc. Empty string is "not set", validated (rejected before persistence)
	// when non-empty and not a valid http(s) URL.
	CallbackUrl   string `protobuf:"bytes,11,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreatePaymentRequest) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreatePaymentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreatePaymentRequest) GetSourceApp() string {
	if x != nil {
		return x.SourceApp
	}
	return ""
}

func (x *CreatePaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePaymentRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type CreatePaymentResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PaymentId string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// status is the domain payment.Status value verbatim (pending, processing,
	// succeeded, failed) — a plain string, not an enum, so it can never drift
	// out of sync with internal/domain/payment/statemachine.go's own strings.
	Status      string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ProviderRef string `protobuf:"bytes,3,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	// replayed has no REST equivalent field (REST signals this via 200-vs-202
	// instead, see CreatePaymentOutput's json:"-" tag) — gRPC has no analogous
	// per-call status-code channel available to a handler, so it is a real
	// response field here. Deliberate transport-level divergence.
	Replayed      bool `protobuf:"varint,4,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentResponse) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *CreatePaymentResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Livemode      bool                   `protobuf:"varint,3,opt,name=livemode,proto3" json:"livemode,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	OperationType string                 `protobuf:"bytes,6,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	Provider      string                 `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRef   string                 `protobuf:"bytes,8,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	// Envelope fields (see payment.Envelope's doc), exposed verbatim —
	// mirrors REST's paymentView.
	SourceApp        string `protobuf:"bytes,10,opt,name=source_app,json=sourceApp,proto3" json:"source_app,omitempty"`
	Channel          string `protobuf:"bytes,11,opt,name=channel,proto3" json:"channel,omitempty"`
	TraceId          string `protobuf:"bytes,12,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Description      string `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	InitiatedBy      string `protobuf:"bytes,14,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"`
	RequestIp        string `protobuf:"bytes,15,opt,name=request_ip,json=requestIp,proto3" json:"request_ip,omitempty"`
	RequestUserAgent string `protobuf:"bytes,16,opt,name=request_user_agent,json=requestUserAgent,proto3" json:"request_user_agent,omitempty"`
	// payment_method/method_payload/callback_url mirror REST's paymentView --
	// see internal/domain/payment.Payment's doc for each field. Empty
	// string / absent nested message is proto3's natural "not set"; a gRPC
	// client distinguishes "no method_payload" from "empty MethodPayload" via
	// the generated GetMethodPayload() nil-check, same shape as REST's JSON
	// null.
	PaymentMethod string         `protobuf:"bytes,17,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	MethodPayload *MethodPayload `protobuf:"bytes,18,opt,name=method_payload,json=methodPayload,proto3" json:"method_payload,omitempty"`
	CallbackUrl   string         `protobuf:"bytes,19,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetPaymentResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetPaymentResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *GetPaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetPaymentResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPaymentResponse) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *GetPaymentResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetPaymentResponse) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *GetPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPaymentResponse) GetSourceApp() string {
	if x != nil {
		return x.SourceApp
	}
	return ""
}

func (x *GetPaymentResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GetPaymentResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetPaymentResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetPaymentResponse) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *GetPaymentResponse) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

func (x *GetPaymentResponse) GetRequestUserAgent() string {
	if x != nil {
		return x.RequestUserAgent
	}
	return ""
}

func (x *GetPaymentResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *GetPaymentResponse) GetMethodPayload() *MethodPayload {
	if x != nil {
		return x.MethodPayload
	}
	return nil
}

func (x *GetPaymentResponse) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

// MethodPayload mirrors internal/provider/payload.MethodPayload: only the
// nested message matching method is set, the rest left absent (proto3's
// analogue of REST's "rest are nil -> JSON null").
type MethodPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Method         string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Qris           *QRIS                  `protobuf:"bytes,2,opt,name=qris,proto3" json:"qris,omitempty"`
	VirtualAccount *VirtualAccount        `protobuf:"bytes,3,opt,name=virtual_account,json=virtualAccount,proto3" json:"virtual_account,omitempty"`
	Card           *Card                  `protobuf:"bytes,4,opt,name=card,proto3" json:"card,omitempty"`
	Ewallet        *EWallet               `protobuf:"bytes,5,opt,name=ewallet,proto3" json:"ewallet,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MethodPayload) Reset() {
	*x = MethodPayload{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodPayload) ProtoMessage() {}

func (x *MethodPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodPayload.ProtoReflect.Descriptor instead.
func (*MethodPayload) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *MethodPayload) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MethodPayload) GetQris() *QRIS {
	if x != nil {
		return x.Qris
	}
	return nil
}

func (x *MethodPayload) GetVirtualAccount() *VirtualAccount {
	if x != nil {
		return x.VirtualAccount
	}
	return nil
}

func (x *MethodPayload) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *MethodPayload) GetEwallet() *EWallet {
	if x != nil {
		return x.Ewallet
	}
	return nil
}

// QRIS mirrors internal/provider/payload.QRIS. expires_at is RFC3339,
// empty string = absent (a plain string, not google.protobuf.Timestamp, to
// avoid a WKT import/timestamppb conversion for a template this small).
type QRIS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrString      string                 `protobuf:"bytes,1,opt,name=qr_string,json=qrString,proto3" json:"qr_string,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRIS) Reset() {
	*x = QRIS{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRIS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRIS) ProtoMessage() {}

func (x *QRIS) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRIS.ProtoReflect.Descriptor instead.
func (*QRIS) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *QRIS) GetQrString() string {
	if x != nil {
		return x.QrString
	}
	return ""
}

func (x *QRIS) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// VirtualAccount mirrors internal/provider/payload.VirtualAccount.
type VirtualAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankCode      string                 `protobuf:"bytes,1,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	VaNumber      string                 `protobuf:"bytes,2,opt,name=va_number,json=vaNumber,proto3" json:"va_number,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualAccount) Reset() {
	*x = VirtualAccount{}
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualAccount) ProtoMessage() {}

func (x *VirtualAccount) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualAccount.ProtoReflect.Descriptor instead.
func (*VirtualAccount) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *VirtualAccount) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *VirtualAccount) GetVaNumber() string {
	if x != nil {
		return x.VaNumber
	}
	return ""
}

func (x *VirtualAccount) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// Card mirrors internal/provider/payload.Card. masked_pan is display-only
// (e.g. "411111******1111") — see provider.go's PCI-DSS scope note.
type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaskedPan     string                 `protobuf:"bytes,1,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *Card) GetMaskedPan() string {
	if x != nil {
		return x.MaskedPan
	}
	return ""
}

func (x *Card) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

// EWallet mirrors internal/provider/payload.EWallet.
type EWallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUrl   string                 `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EWallet) Reset() {
	*x = EWallet{}
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EWallet) ProtoMessage() {}

func (x *EWallet) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EWallet.ProtoReflect.Descriptor instead.
func (*EWallet) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *EWallet) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *EWallet) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// CreateRefundRequest deliberately has no tenant_id/livemode field — same as
// REST's CreateRefundInput, those are derived server-side from the locked
// parent payment row (see rest/refund.go's handleCreateRefund), never taken
// from the caller, so a request can't point a refund at another tenant.
type CreateRefundRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	PaymentId      string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount         int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// source_app/description mirror CreatePaymentRequest's fields — see
	// payment.Envelope's doc.
	SourceApp     string `protobuf:"bytes,5,opt,name=source_app,json=sourceApp,proto3" json:"source_app,omitempty"`
	Description   string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundRequest) Reset() {
	*x = CreateRefundRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundRequest) ProtoMessage() {}

func (x *CreateRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundRequest.ProtoReflect.Descriptor instead.
func (*CreateRefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRefundRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateRefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateRefundRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRefundRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateRefundRequest) GetSourceApp() string {
	if x != nil {
		return x.SourceApp
	}
	return ""
}

func (x *CreateRefundRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Replayed      bool                   `protobuf:"varint,4,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundResponse) Reset() {
	*x = CreateRefundResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundResponse) ProtoMessage() {}

func (x *CreateRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundResponse.ProtoReflect.Descriptor instead.
func (*CreateRefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *CreateRefundResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateRefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRefundResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type GetRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundRequest) Reset() {
	*x = GetRefundRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundRequest) ProtoMessage() {}

func (x *GetRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundRequest.ProtoReflect.Descriptor instead.
func (*GetRefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{11}
}

func (x *GetRefundRequest) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

type GetRefundResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RefundId          string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	PaymentId         string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	TenantId          string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Livemode          bool                   `protobuf:"varint,4,opt,name=livemode,proto3" json:"livemode,omitempty"`
	Currency          string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount            int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Provider          string                 `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRef       string                 `protobuf:"bytes,8,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	ProviderRefundRef string                 `protobuf:"bytes,9,opt,name=provider_refund_ref,json=providerRefundRef,proto3" json:"provider_refund_ref,omitempty"`
	Status            string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	// Envelope fields (see payment.Envelope's doc), exposed verbatim —
	// mirrors REST's refundView.
	SourceApp        string `protobuf:"bytes,11,opt,name=source_app,json=sourceApp,proto3" json:"source_app,omitempty"`
	Channel          string `protobuf:"bytes,12,opt,name=channel,proto3" json:"channel,omitempty"`
	TraceId          string `protobuf:"bytes,13,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Description      string `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	InitiatedBy      string `protobuf:"bytes,15,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"`
	RequestIp        string `protobuf:"bytes,16,opt,name=request_ip,json=requestIp,proto3" json:"request_ip,omitempty"`
	RequestUserAgent string `protobuf:"bytes,17,opt,name=request_user_agent,json=requestUserAgent,proto3" json:"request_user_agent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRefundResponse) Reset() {
	*x = GetRefundResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundResponse) ProtoMessage() {}

func (x *GetRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundResponse.ProtoReflect.Descriptor instead.
func (*GetRefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{12}
}

func (x *GetRefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *GetRefundResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetRefundResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetRefundResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *GetRefundResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetRefundResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetRefundResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetRefundResponse) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *GetRefundResponse) GetProviderRefundRef() string {
	if x != nil {
		return x.ProviderRefundRef
	}
	return ""
}

func (x *GetRefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetRefundResponse) GetSourceApp() string {
	if x != nil {
		return x.SourceApp
	}
	return ""
}

func (x *GetRefundResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GetRefundResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetRefundResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetRefundResponse) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *GetRefundResponse) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

func (x *GetRefundResponse) GetRequestUserAgent() string {
	if x != nil {
		return x.RequestUserAgent
	}
	return ""
}

// CreatePayoutRequest has no counterpart-derived fields (unlike
// CreateRefundRequest): a payout is standalone, so provider/destination are
// caller-supplied here, not derived server-side from a parent row.
// CreatePayoutRequest has no tenant_id field -- see CreatePaymentRequest's
// doc, identical reasoning.
type CreatePayoutRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Livemode       bool                   `protobuf:"varint,3,opt,name=livemode,proto3" json:"livemode,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount         int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Provider       string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	Destination    string                 `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// source_app/description mirror CreatePaymentRequest's fields — see
	// payment.Envelope's doc.
	SourceApp   string `protobuf:"bytes,9,opt,name=source_app,json=sourceApp,proto3" json:"source_app,omitempty"`
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// callback_url mirrors CreatePaymentRequest's field — see
	// payment.CreatePayoutInput.CallbackURL's doc.
	CallbackUrl   string `protobuf:"bytes,11,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayoutRequest) Reset() {
	*x = CreatePayoutRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayoutRequest) ProtoMessage() {}

func (x *CreatePayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayoutRequest.ProtoReflect.Descriptor instead.
func (*CreatePayoutRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePayoutRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreatePayoutRequest) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *CreatePayoutRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePayoutRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePayoutRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreatePayoutRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreatePayoutRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreatePayoutRequest) GetSourceApp() string {
	if x != nil {
		return x.SourceApp
	}
	return ""
}

func (x *CreatePayoutRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePayoutRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type CreatePayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutId      string                 `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ProviderRef   string                 `protobuf:"bytes,3,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	Replayed      bool                   `protobuf:"varint,4,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayoutResponse) Reset() {
	*x = CreatePayoutResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayoutResponse) ProtoMessage() {}

func (x *CreatePayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayoutResponse.ProtoReflect.Descriptor instead.
func (*CreatePayoutResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePayoutResponse) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

func (x *CreatePayoutResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePayoutResponse) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *CreatePayoutResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type GetPayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutId      string                 `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayoutRequest) Reset() {
	*x = GetPayoutRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutRequest) ProtoMessage() {}

func (x *GetPayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutRequest.ProtoReflect.Descriptor instead.
func (*GetPayoutRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{15}
}

func (x *GetPayoutRequest) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

type GetPayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutId      string                 `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Livemode      bool                   `protobuf:"varint,3,opt,name=livemode,proto3" json:"livemode,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	OperationType string                 `protobuf:"bytes,6,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	Provider      string                 `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRef   string                 `protobuf:"bytes,8,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	Destination   string                 `protobuf:"bytes,9,opt,name=destination,proto3" json:"destination,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	// Envelope fields (see payment.Envelope's doc), exposed verbatim —
	// mirrors REST's payoutView.
	SourceApp        string `protobuf:"bytes,11,opt,name=source_app,json=sourceApp,proto3" json:"source_app,omitempty"`
	Channel          string `protobuf:"bytes,12,opt,name=channel,proto3" json:"channel,omitempty"`
	TraceId          string `protobuf:"bytes,13,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Description      string `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	InitiatedBy      string `protobuf:"bytes,15,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"`
	RequestIp        string `protobuf:"bytes,16,opt,name=request_ip,json=requestIp,proto3" json:"request_ip,omitempty"`
	RequestUserAgent string `protobuf:"bytes,17,opt,name=request_user_agent,json=requestUserAgent,proto3" json:"request_user_agent,omitempty"`
	// callback_url mirrors REST's payoutView. A payout has no
	// payment_method/method_payload analogue -- see payoutView's doc.
	CallbackUrl   string `protobuf:"bytes,18,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayoutResponse) Reset() {
	*x = GetPayoutResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutResponse) ProtoMessage() {}

func (x *GetPayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutResponse.ProtoReflect.Descriptor instead.
func (*GetPayoutResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{16}
}

func (x *GetPayoutResponse) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

func (x *GetPayoutResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetPayoutResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *GetPayoutResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetPayoutResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPayoutResponse) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *GetPayoutResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetPayoutResponse) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *GetPayoutResponse) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *GetPayoutResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPayoutResponse) GetSourceApp() string {
	if x != nil {
		return x.SourceApp
	}
	return ""
}

func (x *GetPayoutResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GetPayoutResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetPayoutResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetPayoutResponse) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *GetPayoutResponse) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

func (x *GetPayoutResponse) GetRequestUserAgent() string {
	if x != nil {
		return x.RequestUserAgent
	}
	return ""
}

func (x *GetPayoutResponse) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\"\xd0\x03\n" +
	"\x14CreatePaymentRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\blivemode\x18\x03 \x01(\bR\blivemode\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12%\n" +
	"\x0epayment_method\x18\a \x01(\tR\rpaymentMethod\x12J\n" +
	"\bmetadata\x18\b \x03(\v2..payment.v1.CreatePaymentRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"source_app\x18\t \x01(\tR\tsourceApp\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12!\n" +
	"\fcallback_url\x18\v \x01(\tR\vcallbackUrl\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03R\ttenant_id\"\x8d\x01\n" +
	"\x15CreatePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fprovider_ref\x18\x03 \x01(\tR\vproviderRef\x12\x1a\n" +
	"\breplayed\x18\x04 \x01(\bR\breplayed\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\x90\x05\n" +
	"\x12GetPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\blivemode\x18\x03 \x01(\bR\blivemode\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12%\n" +
	"\x0eoperation_type\x18\x06 \x01(\tR\roperationType\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12!\n" +
	"\fprovider_ref\x18\b \x01(\tR\vproviderRef\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"source_app\x18\n" +
	" \x01(\tR\tsourceApp\x12\x18\n" +
	"\achannel\x18\v \x01(\tR\achannel\x12\x19\n" +
	"\btrace_id\x18\f \x01(\tR\atraceId\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12!\n" +
	"\finitiated_by\x18\x0e \x01(\tR\vinitiatedBy\x12\x1d\n" +
	"\n" +
	"request_ip\x18\x0f \x01(\tR\trequestIp\x12,\n" +
	"\x12request_user_agent\x18\x10 \x01(\tR\x10requestUserAgent\x12%\n" +
	"\x0epayment_method\x18\x11 \x01(\tR\rpaymentMethod\x12@\n" +
	"\x0emethod_payload\x18\x12 \x01(\v2\x19.payment.v1.MethodPayloadR\rmethodPayload\x12!\n" +
	"\fcallback_url\x18\x13 \x01(\tR\vcallbackUrl\"\xe7\x01\n" +
	"\rMethodPayload\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12$\n" +
	"\x04qris\x18\x02 \x01(\v2\x10.payment.v1.QRISR\x04qris\x12C\n" +
	"\x0fvirtual_account\x18\x03 \x01(\v2\x1a.payment.v1.VirtualAccountR\x0evirtualAccount\x12$\n" +
	"\x04card\x18\x04 \x01(\v2\x10.payment.v1.CardR\x04card\x12-\n" +
	"\aewallet\x18\x05 \x01(\v2\x13.payment.v1.EWalletR\aewallet\"B\n" +
	"\x04QRIS\x12\x1b\n" +
	"\tqr_string\x18\x01 \x01(\tR\bqrString\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"i\n" +
	"\x0eVirtualAccount\x12\x1b\n" +
	"\tbank_code\x18\x01 \x01(\tR\bbankCode\x12\x1b\n" +
	"\tva_number\x18\x02 \x01(\tR\bvaNumber\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"H\n" +
	"\x04Card\x12\x1d\n" +
	"\n" +
	"masked_pan\x18\x01 \x01(\tR\tmaskedPan\x12!\n" +
	"\fredirect_url\x18\x02 \x01(\tR\vredirectUrl\"K\n" +
	"\aEWallet\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"\xd2\x01\n" +
	"\x13CreateRefundRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"source_app\x18\x05 \x01(\tR\tsourceApp\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\x86\x01\n" +
	"\x14CreateRefundResponse\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\breplayed\x18\x04 \x01(\bR\breplayed\"/\n" +
	"\x10GetRefundRequest\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\"\xa9\x04\n" +
	"\x11GetRefundResponse\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1a\n" +
	"\blivemode\x18\x04 \x01(\bR\blivemode\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12!\n" +
	"\fprovider_ref\x18\b \x01(\tR\vproviderRef\x12.\n" +
	"\x13provider_refund_ref\x18\t \x01(\tR\x11providerRefundRef\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"source_app\x18\v \x01(\tR\tsourceApp\x12\x18\n" +
	"\achannel\x18\f \x01(\tR\achannel\x12\x19\n" +
	"\btrace_id\x18\r \x01(\tR\atraceId\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12!\n" +
	"\finitiated_by\x18\x0f \x01(\tR\vinitiatedBy\x12\x1d\n" +
	"\n" +
	"request_ip\x18\x10 \x01(\tR\trequestIp\x12,\n" +
	"\x12request_user_agent\x18\x11 \x01(\tR\x10requestUserAgent\"\xc9\x03\n" +
	"\x13CreatePayoutRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\blivemode\x18\x03 \x01(\bR\blivemode\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12 \n" +
	"\vdestination\x18\a \x01(\tR\vdestination\x12I\n" +
	"\bmetadata\x18\b \x03(\v2-.payment.v1.CreatePayoutRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"source_app\x18\t \x01(\tR\tsourceApp\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12!\n" +
	"\fcallback_url\x18\v \x01(\tR\vcallbackUrl\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03R\ttenant_id\"\x8a\x01\n" +
	"\x14CreatePayoutResponse\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fprovider_ref\x18\x03 \x01(\tR\vproviderRef\x12\x1a\n" +
	"\breplayed\x18\x04 \x01(\bR\breplayed\"/\n" +
	"\x10GetPayoutRequest\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\"\xc6\x04\n" +
	"\x11GetPayoutResponse\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\blivemode\x18\x03 \x01(\bR\blivemode\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12%\n" +
	"\x0eoperation_type\x18\x06 \x01(\tR\roperationType\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12!\n" +
	"\fprovider_ref\x18\b \x01(\tR\vproviderRef\x12 \n" +
	"\vdestination\x18\t \x01(\tR\vdestination\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"source_app\x18\v \x01(\tR\tsourceApp\x12\x18\n" +
	"\achannel\x18\f \x01(\tR\achannel\x12\x19\n" +
	"\btrace_id\x18\r \x01(\tR\atraceId\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12!\n" +
	"\finitiated_by\x18\x0f \x01(\tR\vinitiatedBy\x12\x1d\n" +
	"\n" +
	"request_ip\x18\x10 \x01(\tR\trequestIp\x12,\n" +
	"\x12request_user_agent\x18\x11 \x01(\tR\x10requestUserAgent\x12!\n" +
	"\fcallback_url\x18\x12 \x01(\tR\vcallbackUrl2\xed\x03\n" +
	"\x0ePaymentService\x12T\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a!.payment.v1.CreatePaymentResponse\x12K\n" +
	"\n" +
	"GetPayment\x12\x1d.payment.v1.GetPaymentRequest\x1a\x1e.payment.v1.GetPaymentResponse\x12Q\n" +
	"\fCreateRefund\x12\x1f.payment.v1.CreateRefundRequest\x1a .payment.v1.CreateRefundResponse\x12H\n" +
	"\tGetRefund\x12\x1c.payment.v1.GetRefundRequest\x1a\x1d.payment.v1.GetRefundResponse\x12Q\n" +
	"\fCreatePayout\x12\x1f.payment.v1.CreatePayoutRequest\x1a .payment.v1.CreatePayoutResponse\x12H\n" +
	"\tGetPayout\x12\x1c.payment.v1.GetPayoutRequest\x1a\x1d.payment.v1.GetPayoutResponseB?Z=Fisher-Mapper/internal/transport/grpc/pb/payment/v1;paymentv1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_payment_v1_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),  // 0: payment.v1.CreatePaymentRequest
	(*CreatePaymentResponse)(nil), // 1: payment.v1.CreatePaymentResponse
	(*GetPaymentRequest)(nil),     // 2: payment.v1.GetPaymentRequest
	(*GetPaymentResponse)(nil),    // 3: payment.v1.GetPaymentResponse
	(*MethodPayload)(nil),         // 4: payment.v1.MethodPayload
	(*QRIS)(nil),                  // 5: payment.v1.QRIS
	(*VirtualAccount)(nil),        // 6: payment.v1.VirtualAccount
	(*Card)(nil),                  // 7: payment.v1.Card
	(*EWallet)(nil),               // 8: payment.v1.EWallet
	(*CreateRefundRequest)(nil),   // 9: payment.v1.CreateRefundRequest
	(*CreateRefundResponse)(nil),  // 10: payment.v1.CreateRefundResponse
	(*GetRefundRequest)(nil),      // 11: payment.v1.GetRefundRequest
	(*GetRefundResponse)(nil),     // 12: payment.v1.GetRefundResponse
	(*CreatePayoutRequest)(nil),   // 13: payment.v1.CreatePayoutRequest
	(*CreatePayoutResponse)(nil),  // 14: payment.v1.CreatePayoutResponse
	(*GetPayoutRequest)(nil),      // 15: payment.v1.GetPayoutRequest
	(*GetPayoutResponse)(nil),     // 16: payment.v1.GetPayoutResponse
	nil,                           // 17: payment.v1.CreatePaymentRequest.MetadataEntry
	nil,                           // 18: payment.v1.CreatePayoutRequest.MetadataEntry
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	17, // 0: payment.v1.CreatePaymentRequest.metadata:type_name -> payment.v1.CreatePaymentRequest.MetadataEntry
	4,  // 1: payment.v1.GetPaymentResponse.method_payload:type_name -> payment.v1.MethodPayload
	5,  // 2: payment.v1.MethodPayload.qris:type_name -> payment.v1.QRIS
	6,  // 3: payment.v1.MethodPayload.virtual_account:type_name -> payment.v1.VirtualAccount
	7,  // 4: payment.v1.MethodPayload.card:type_name -> payment.v1.Card
	8,  // 5: payment.v1.MethodPayload.ewallet:type_name -> payment.v1.EWallet
	18, // 6: payment.v1.CreatePayoutRequest.metadata:type_name -> payment.v1.CreatePayoutRequest.MetadataEntry
	0,  // 7: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	2,  // 8: payment.v1.PaymentService.GetPayment:input_type -> payment.v1.GetPaymentRequest
	9,  // 9: payment.v1.PaymentService.CreateRefund:input_type -> payment.v1.CreateRefundRequest
	11, // 10: payment.v1.PaymentService.GetRefund:input_type -> payment.v1.GetRefundRequest
	13, // 11: payment.v1.PaymentService.CreatePayout:input_type -> payment.v1.CreatePayoutRequest
	15, // 12: payment.v1.PaymentService.GetPayout:input_type -> payment.v1.GetPayoutRequest
	1,  // 13: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.CreatePaymentResponse
	3,  // 14: payment.v1.PaymentService.GetPayment:output_type -> payment.v1.GetPaymentResponse
	10, // 15: payment.v1.PaymentService.CreateRefund:output_type -> payment.v1.CreateRefundResponse
	12, // 16: payment.v1.PaymentService.GetRefund:output_type -> payment.v1.GetRefundResponse
	14, // 17: payment.v1.PaymentService.CreatePayout:output_type -> payment.v1.CreatePayoutResponse
	16, // 18: payment.v1.PaymentService.GetPayout:output_type -> payment.v1.GetPayoutResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
